name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
    - name: Print grettings
      run: | 
       echo "Hello World!"
       echo "Young Money World!"
    - name: Print goodbye
      run: echo "Done - bye!"
